version: '3.8'

services:
  fastapi:
    build: ./fastapi-backend
    ports:
      - "8000:8000"
    depends_on:
      - n8n

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
